baseURL: http://example.org/
languageCode: en-us
title: David Gallay
theme: PaperMod
# taxonomies:
#   category: categories
#   tag: tags
#   series: series
params:
  disableSpecial1stPost: true  # Do not treats first post differently
  ShowToc: true
  # foldable: false
  ShowCodeCopyButtons: true # Adds a copy button in code block to copy the code it contains
  ShowPostNavLinks: true  # Adds a Previous / Next post suggestion under a single post
  ShowBreadCrumbs: true
  ShowShareButtons: true
  # homeInfoParams:
  #   Title: Hi there wave
  #   Content: Can be Info, links, about...

  profileMode:
      enabled: false
      title: PaperMod
      imageUrl: "#"
      imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      # buttons:
      #     - name: Archives
      #       url: archives
      #     - name: Tags
      #       url: tags

  homeInfoParams:
      Title: "David Gallay"
      Content: >
          Hi and welcome on my blog / online CV. Contact me if you want!
          Good reading.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/divad1196"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/david-gallay-4244bb1a7/"
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
menu:
  # https://github.com/adityatelange/hugo-PaperMod/issues/947
  main:
    - identifier: archives
      name: Archives
      url: /archives/
    # - ..
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - name: Tags
      url: tags/
      weight: 10